### PR TITLE
Quick fix for isomorphism

### PR DESCRIPTION
**Pull request by orourkedd**
It breaks node when I'm using this with an isomorphic react app.  It would be great to make it non-op in this case.

### CODE REVIEW

**Comment by desandro** [comment]
Thanks for the contribution! React is out of my comfort zone. I'm curious, [maybe changing `window` to `this`](https://github.com/desandro/draggabilly/blob/v1.2.4/draggabilly.js#L42) would be a better solution?

**Comment by orourkedd** [comment]
I'm not sure it would be necessary because this module has no purpose in the node environment.  Simply making it not crash node should be good enough.  Thoughts?

**Comment by desandro** [comment]
If that's the case, I feel like the conditional should be higher up — this module shouldn't be loaded in the first place

**Comment by orourkedd** [comment]
Perhaps you're right. The issue seems to me that since the module is on npm it should work in node (or at least not fail).  When I try to load it using a require(...) statement, however, it fails.  This means that it can't be used with browserify unless it is loaded into the global scope and shimmed.  A lot of modules which rely on window, document, navigator, etc, (like jquery), will gracefully degrade when loaded into node to allow for easy building with browserify, etc.

**Comment by desandro** [comment]
Thanks again for this contribution, but I've decided not to move forward with this patch. :whale:

**Pull request closed without merging**
